global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
  
  - job_name: 'nodejs-app'
    static_configs:
      - targets: ['172.17.0.1:3000']
    metrics_path: '/metrics'
  
  - job_name: 'spring-app'
    static_configs:
      - targets: ['172.17.0.1:8080']
    metrics_path: '/actuator/prometheus'
